### PR TITLE
Fix docker build and prow testing

### PR DESCRIPTION
**Pull request by tonytheleg**
All changes were to correct issues with prow results and binary/container building. This will get the code base to a good state which will allow for others to be able to contribute code changes, and have healthy results in PR's and be able to merge.

Issues addressed:
* Pulls in Katherines changes from [PR 8](https://github.com/openshift/configure-goalert-operator/pull/8)
* Local binary builds were failing due to package import declarations
* Container builds were failing due to some needed directories not being copied over to the build container (`pkg`, `config`)
* Prow Lint tests were fixed by either commenting out sections of unused logic/code, or exporting objects in packages that were not used in those packages (lint saw them as being unused -- many of these we may want to keep exported anyway)
*  Local runs of prow validate, coverage, lint, and test were all successful after changes (can be tested using `make container-lint`, `make container-test`, `make container-validate`, `make container-coverage`)
* Bumps ubi-micro version (renders [PR 6](https://github.com/openshift/configure-goalert-operator/pull/6) obsolete)

### CODE REVIEW

**Comment by tonytheleg** [comment]
In order to fix the coverage test, I think we'll need to ensure these steps were done, looks like some are not setup yet
https://github.com/openshift/ops-sop/blob/master/services/codecov.md#generate-the-codecovio-token

**Comment by mjlshen** [comment]
A `go mod tidy` should fix this + https://github.com/openshift/release/pull/39842

**Pull request merged**
